version: 2
jobs:
  build:
    docker:
      - image: epitechcontent/epitest-docker
    steps:
      - checkout
      - run:
          name: Build Project
          command: make
      - run:
          name: Build Unit Tests Suites
          command: make tests
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~

  test:
    docker:
      - image: epitechcontent/epitest-docker
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # - run:
      #     name: Unit Tests Execution
      #     command: ./nm/unit_tests.out
      # - run:
      #     name: Unit Tests Execution
      #     command: ./objdump/unit_tests.out
      # kappa
      - run:
          name: Run Functionnal tests
          command: ./tests/functionnal_tests.sh
      - run:
          name: Run Functionnal tests
          command: ./tests/functionnal_tests2.sh

  epitest:
    docker:
      - image: epitechcontent/epitest-docker
    steps:
      - checkout
      - run:
          name: Build Project
          command: make
      - run:
          name: Tidy up
          command: make clean
      - run:
          name: Run Functionnal tests
          command: ./tests/functionnal_tests.sh
      - run:
          name: Run Functionnal tests
          command: ./tests/functionnal_tests2.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  planned:
    triggers:
      - schedule:
          cron: "0 22 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - epitest
